### PR TITLE
Adds custom column support to ShotgunModel

### PR DESCRIPTION
**Pull request by agibli**
From the previous pull request: "Manne had expressed interest in this so I whipped something up. The main thing of note is that this doesn't include the additional columns in the disk file (too big of a change), which may or may not be what you'd want for this feature. Let me know if it looks okay!"

Apologies for the bogus pull request earlier.

### CODE REVIEW

**Comment by alandann** [comment]
Hi Alon,

I'm in the process of pulling this stuff in but I might hold off on this one for a little while... I need column support for the new file manager so it's likely I will end up implementing the full cached-to-disk version but let me take a look and get back to you.

Thanks
Alan

**Comment by agibli** [comment]
Hi Alan,

No worries! There isn't much urgency on this from our end, in fact you are welcome to close this request if you don't think it will be merged. I haven't done it yet, but I would like to try implementing additional columns using a proxy model, so that we can run an unmodified shotgunutils until full column support is implemented. I'll let you know how that goes!

**Comment by alandann** [comment]
Hi Alon,

I'll leave this open for now and we have an internal ticket tracking adding support for columns.

Thanks
Alan

**Comment by robblau** [comment]
Columns are now officially in.  Just did it as part of a different pull request.
Thanks Alon!

**Comment by agibli** [comment]
Awesome! Can't wait to try it out :)

**Pull request closed without merging**
